call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" colors
set background=light
let g:solarized_termtrans=1
let g:solarized_termcolors=256
"let g:solarized_contrast="high"
"let g:solarized_visibility="high"
colorscheme solarized

" command-t
noremap <leader>o <Esc>:CommandT<CR>
noremap <leader>O <Esc>:CommandTFlush<CR>
noremap <leader>m <Esc>:CommandTBuffer<CR>

" Omni and SuperTab
filetype plugin on
set ofu=syntaxcomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabContextDefaultCompletionType = "user"

" Code Folding
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

" Alex's Stuf----------------------------------------------------------
set nocompatible
set nobackup

" encoding
set encoding=utf-8
set fileencoding=utf-8

" file format
set fileformats=unix,dos

" search
set ignorecase
set smartcase
set incsearch
set hlsearch

" gui
set number " line numbers
set ruler " show line and column number of the cursor position
" set cursorline
set showcmd
set wildmenu
set list listchars=tab:»·,trail:·
set diffopt=filler,vertical,iwhite

" whitespace
set expandtab " use spaces instead of tabs
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smarttab " inserts blanks according to shiftwidth in front of a line

" syntax highlighting
syntax on
filetype plugin on

" indentation
set autoindent " copy indent from current line when starting a new line
set backspace=2

" mappings
map <c-a> ggVG
imap <c-a> <Esc>ggVG
map <c-PageDown> gt
map <c-PageUp> gT
imap <c-PageDown> <Esc>gt
imap <c-PageUp> <Esc>gT

" moving to the right place
" set autochdir
set rnu

